// NextJs
import Head from 'next/head';

// Components
import CardComponent from '@/components/CardComponent';
import Header from '@/components/global/Header';
import Footer from '@/components/global/Footer';

export default function Home() {
  const VisionFeatures = [
    {
      title: 'Image Classification',
      description: 'Classify images with labels from the ImageNet database. (MobileNet)',
      link: 'test/ImageClassification',
      imageUrl: 'https://www.tensorflow.org/static/site-assets/images/marketing/icon/tile_model_image.png'
    }, {
      title: 'Object Detection',
      description: 'Locate and identify multiple objects in a single image. (Coco-SSD)',
      link: 'test/ObjectDetection',
      imageUrl: 'https://www.tensorflow.org/static/site-assets/images/marketing/icon/tile_model_shapes.png'
    }, {
      title: 'Semantic Segmentation',
      description: 'Run semantic image segmentation on an image to classify each pixel.',
      link: 'test/SemanticSegmentation',
      imageUrl: 'https://www.tensorflow.org/static/site-assets/images/marketing/icon/tile_model_people.png'
    }
  ];

  return (
    <>
      <Head>
        <title>Objectify</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='min-h-screen bg-gray-100 flex flex-col justify-between'>
        <Header />

        <div className="py-10">
          <div className="max-w-7xl mx-auto sm:px-6 lg:px-8">

            <div className="px-4 py-6 sm:px-0 flex flex-col items-center mb-4">
              <h1 className="text-3xl font-bold leading-tight text-gray-900/60">Vision</h1>
              <p className="mt-1 max-w-2xl text-sm text-gray-500">
                Analyze features in images and videos. Unlock new real-time experiences in the browser.
              </p>
            </div>

            <div className="grid grid-cols-1 gap-5 lg:grid-cols-3 justify-items-center">
              {VisionFeatures.map((card, _idx) => (
                <CardComponent key={_idx} card={card} />
              ))}
            </div>
          </div>
        </div>

        <Footer />

      </main>
    </>
  );
}
