import Footer from '@/components/global/Footer';
import Header from '@/components/global/Header';
import Head from 'next/head';
import { useRouter } from 'next/router';


export default function ClassifyAndDetect() {
    const router = useRouter();
    let { id } = router.query;

    id = id?.replace(/-/g, ' ');

    return (
        <>
            <Head>
                <title>Objectify - {id}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className='min-h-screen bg-gray-100 flex flex-col justify-between'>
                <Header />

                <div className="py-10">
                    <div className="max-w-7xl mx-auto sm:px-6 lg:px-8">
                        <div className="px-4 py-6 sm:px-0 flex flex-col items-center mb-4">
                            <h1 className="text-3xl font-bold leading-tight text-gray-900/60">{id}</h1>
                            <p className="mt-1 max-w-2xl text-sm text-gray-500">
                                Analyze features in images and videos. Unlock new real-time experiences in the browser.
                            </p>
                        </div>
                    </div>
                </div>

                <Footer />
            </main>
        </>
    );
}
